### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by Dimezis** [vivchar/RendererRecyclerViewAdapter#1]
I really appreciate the idea, but I just have to ask, what's the idea behind this kind of formatting?

```
public
class SomeViewHolder
		extends RecyclerView.ViewHolder
{
```

At the same time, fields have "regular" formatting:

```
public final TextView mTitle;
```

Probably from library-user perspective it doesn't really matter, but it's still kinda hard to read.

**Comment by vivchar** [comment]
@Dimezis thanks. Maybe it's hard to read, but it helps when working with git and code review.
