### ISSUE TITLE
How can I register a Renderer without a model?

### ISSUE THREAD

**Issue by duartebarbosadev** [vivchar/RendererRecyclerViewAdapter#10]
Title.
Also, can I use 2 different Binders with the same model?
One more thing, if the layout isn't showing what does it mean?

**Comment by vivchar** [comment]
No, It is not possible, but you can create a workaround for your model.
For example, you have a ViewModel like this:
```java
public class YourModel implements ViewModel {
        /* your code */
}
```

You should extend your model:
```java
public class YourExtentedModel extends YourModel { }
```

Now you can register two ViewRenderers/ViewBinders:
```java
adapter.registerRenderer(new YourViewRenderer(R.layout.your_layout, YourViewModel.class, ...));
adapter.registerRenderer(new YourExtendedViewRenderer(R.layout.your_extended_layout, YourExtendedModel.class, ...));
```

>One more thing, if the layout isn't showing what does it mean?

Look like you have a typo in your code, or missing anything

**Comment by duartebarbosadev** [comment]
One of the registered renderers don't appear.

If I only register TimeUntilEventViewBinder() it works perfectly
![1](https://user-images.githubusercontent.com/13065435/36613452-74c7b1ca-18d1-11e8-9b15-5df933b59782.png)

And if I only register EventUsersViewBinder() it also works perfectly
![2](https://user-images.githubusercontent.com/13065435/36613620-fa5c2276-18d1-11e8-9ad3-a54fa4da70ae.png)

But if I add those 2, I can only see EventUsersViewBinder() (The image above)

this is my code:

        mRecyclerViewAdapter = new RendererRecyclerViewAdapter(getContext());
        mRecyclerViewAdapter.registerRenderer(new TimeUntilEventViewBinder().getMyBinder());
        mRecyclerViewAdapter.registerRenderer(new EventUsersViewBinder().getMyBinder());
        mRecyclerViewAdapter.setItems(getItemsTimeUntil());
        mRecyclerViewAdapter.setItems(getItemsEventUsers());

        mRecyclerViewAdapter.notifyDataSetChanged();

        final RecyclerView recyclerView = view.findViewById(R.id.recycler_viewEvent);
        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(this.getActivity());
        recyclerView.setLayoutManager(mLayoutManager);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(mRecyclerViewAdapter);

**Comment by vivchar** [comment]
Method the `setItems` does not add new items, it replaces previous to new items, so you should call the `setItems` once, and do it after the `setAdapter` call:
```diff
	mRecyclerViewAdapter = new RendererRecyclerViewAdapter(getContext());
	mRecyclerViewAdapter.registerRenderer(new TimeUntilEventViewBinder().getMyBinder());
	mRecyclerViewAdapter.registerRenderer(new EventUsersViewBinder().getMyBinder());
-	mRecyclerViewAdapter.setItems(getItemsTimeUntil());
-	mRecyclerViewAdapter.setItems(getItemsEventUsers());

-	mRecyclerViewAdapter.notifyDataSetChanged();

	final RecyclerView recyclerView = view.findViewById(R.id.recycler_viewEvent);
	RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(this.getActivity());
	recyclerView.setLayoutManager(mLayoutManager);
	recyclerView.setHasFixedSize(true);
	recyclerView.setAdapter(mRecyclerViewAdapter);

+	ArrayList items = new ArrayList();
+	items.addAll(getItemsTimeUntil());
+	items.addAll(getItemsEventUsers());

+	mRecyclerViewAdapter.setItems(items);
+	mRecyclerViewAdapter.notifyDataSetChanged();
```
