### ISSUE TITLE
How to use Glide

### ISSUE THREAD

**Issue by erfannf** [vivchar/RendererRecyclerViewAdapter#11]
I'v inspected examples and found the complex models utilizing Glide. By the way RENDERER is deprecated in latest release and I can not figure out how to use Glide in BINDERS. Any help?

**Comment by vivchar** [comment]
Good question! Thanks.

In my project I am using a CustomView, example:

```java
public class UrlImageView extend ImageView {

	public UrlImageView(Context context) { /* default constructor */
		super(context);
	}

	/* other methods */

	public void setUrl(String url) {
		Glide.with(getContext()).load(url).into(this);
	}
}
```

```java
mRecyclerViewAdapter.registerRenderer(new ViewBinder<>(
	R.layout.item_layout,
	SomeModel.class,
	(model, finder, payloads) -> finder
		.find(R.id.custom_view, (ViewProvider<UrlImageView>) urlImageView -> {
			urlImageView.setUrl(model.getImageUrl());
		})
));
```

OR you can use it:
```java
mRecyclerViewAdapter.registerRenderer(new ViewBinder<>(
	R.layout.item_layout,
	SomeModel.class,
	(model, finder, payloads) -> finder
		.find(R.id.custom_view, (ViewProvider<ImageView>) imageView -> {
			Glide.with(getContext()).load(model.getUrl()).into(imageView);
		})
));
```
OR:
```java
mRecyclerViewAdapter.registerRenderer(new ViewBinder<>(
	R.layout.item_layout,
	SomeModel.class,
	(model, finder, payloads) -> finder {
		ImageView imageView = finder.find(R.id.custom_view);
		Glide.with(getContext()).load(model.getUrl()).into(imageView);
	}
));
```

**Comment by duartebarbosadev** [comment]
Just a small correction
there's a 's' missing in extend (`public class UrlImageView extend ImageView {`)

I have this error: 
android.support.v7.widget.AppCompatImageView cannot be cast to net.quarkapps.ezmeet.customViews.UrlImageView


Edit: I just used another example but I had to use finder.getRootView().getContext()

**Comment by vivchar** [comment]
> android.support.v7.widget.AppCompatImageView cannot be cast to net.quarkapps.ezmeet.customViews.UrlImageView

Looks like you did not replace the AppCompatImageView to the UrlImageView in your xml layout.
