### ISSUE TITLE
How to add sections in Recyclerview

### ISSUE THREAD

**Issue by WasimMemon** [vivchar/RendererRecyclerViewAdapter#14]
I am looking for recyclerview library for my project. But it has specific requirement of sections in recyclerview.
Some time sections should be scroll able and some time sticky sections.
I don't have tried this library that's why not asked on stackoverflow.
But before starting i want to confirm so I don't have to change it later on.

So How to add sections in Recyclerview with your library ?

**Comment by vivchar** [comment]
Sticky Section is not feature of RecyclerViewAdapter, so I don't support it in my adapter.
Sticky Section is a feature of RecyclerView and LayoutManager, you can use any solution to get it.
For example: 
* https://github.com/bgogetap/StickyHeaders
* https://stackoverflow.com/q/32949971/4894238
* http://www.codexpedia.com/android/android-recyclerview-with-sticky-header-using-itemdecoration
