### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by croccio** [vivchar/RendererRecyclerViewAdapter#17]
how can I implement pagination? every time I do setItems recycler view return to top. and if call notifydatasetchanged than nothing change

**Comment by vivchar** [comment]
You should use the DiffUtil, please see bellow:
[Load More Indicator](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-Load-More-Indicator)
[DiffUtil](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-DiffUtil)

Please use the stackoverflow.com for how-to questions.
