### ISSUE TITLE
DefaultDiffCallback with nested RecyclerView

### ISSUE THREAD

**Issue by mengjiin** [vivchar/RendererRecyclerViewAdapter#21]
I tried posting my question to stackoverflow (this is my first time posting to stackoverflow) and I have to yet figure out how to do the formatting on stackoverflow correctly (now it doesn't look right), so I'm asking my question here.

I don't know how to handle the following scenario, please advise.
Thanks for your help!

ParentRecyclerView -> ChildRecyclerView
For each item on the ParentRecyclerView, there is a button to delete the specific parent item
For each item on the ChildRecyclerView, there is a button to delete the specific child item
e.g 

parent item A
--------------------------
| child item C, button C   |
| child item D, button D   |
--------------------------
                            button A

parent item B
--------------------------
| child item E, button E   |
| child item F, button F   |
--------------------------
                           button B

click button A will delete parent item A, click button C will delete child C, and so forth

parentAdapter = new RendererRecyclerViewAdapter();
parentAdapter.setDiffCallback(new ParentDiffCallback());
public class ParentDiffCallback extends DefaultDiffCallback<ParentModel> {
    public boolean areItemsTheSame(@NonNull final ParentModel oldItem, @NonNull 
    final ParentModel newItem) {
	    return oldItem.getId().equals(newItem.getId());
	}
}

When I click on button A, parent item A (including child item C and D) will disappear from the ParentRecyclerView, which is exactly what I want. 
But when I click on button E, I don't know what I should have in ParentDiffCallback to make child item E disappear from the ChildRecyclerView, I want it to look like the following:

parent item B
-------------------------  
| child item F, button F   |
-------------------------
                           button B

I tried the following code and it didn't work:

@Override
public boolean areContentsTheSame(@NonNull final ParentModel oldItem, @NonNull final ParentModel newItem) {
        List<String> old_ids = new ArrayList<>();
        List<String> new_ids = new ArrayList<>();
	for (ChildModel old_cm : oldItem.getItems()) {
            old_ids.add(old_cm.getId());
        }
        for (ChildModel new_cm : newItem.getItems()) {
            new_ids.add(new_cm.getId());
        }
        return old_ids.equals(new_ids);
}

areContentsTheSame always returns true

**Comment by vivchar** [comment]
It is the question for the stackoverflow. Please provide a link to the stackoverflow question and we will continue there.

What do you do after clicking at the remove button? Looks like you don't remove a child item in your list.

FYI: In the `areContentsTheSame` method you should use `oldItem.equals(newItem)` and you should override `equals` method in `ParentModel` and `ChildItem`. It is not critical in your case but is not correct in general. See Google Documentation about DiffUtil.

**Comment by mengjiin** [comment]
Thanks for your reply, I'm still trying to figure out how to post to stackoverflow, so please allow me to ask my question here for the time being.

I'd really appreciate if you could help me proceed, thank you!

=====================================================================

Here is my parent model:

public class ParentModel extends DefaultCompositeViewModel {
    private String id;

    public ParentModel(String id, List<ChildModel> items) {
        super(items);
        this.id = id;
    }

    public String getId() {
        return id;
    }

    @Override
    public List<ChildModel> getItems() {
        return (List<ChildModel>) super.getItems();
    }

    public boolean equals(Object other) {
        if (other instanceof ParentModel) {
            ParentModel pm = (ParentModel) other;
            return pm.getId() == this.getId();
        }
        return false;
    }

=====================================================================

Here is my child model:

public class ChildModel implements ViewModel {
    private String id;
    private String parent_id;

    public ChildModel(String id, String parent_id) {
        this.id = id;
        this.parent_id = parent_id;
    }

    public String getId() { return id; }

    public String getParentId() {
        return parent_id;
    }

    public boolean equals(Object other) {
        if (other instanceof ChildModel) {
            ChildModel cm = (ChildModel) other;
            return cm.getId() == this.getId();
        }
        return false;
    }
}

=====================================================================

Here is my ParentDiffCallback (I changed areContentsTheSame based on your advice):

public class ParentDiffCallback extends DefaultDiffCallback<ParentModel> {
	@Override
	public boolean areItemsTheSame(@NonNull final ParentModel oldItem, @NonNull final ParentModel newItem) {
	    return oldItem.getId().equals(newItem.getId());
	}

	@Override
	public boolean areContentsTheSame(@NonNull final ParentModel oldItem, @NonNull final ParentModel newItem) {
		return oldItem.equals(newItem);
	}

	@Nullable
	@Override
	public Object getChangePayload(@NonNull final ParentModel oldItem, @NonNull final ParentModel newItem) {
		return null;
	}
}

=====================================================================

Here is my child view renderer (I did remove child item with the click, please tell me if I did it wrong):
parentModels is the list of parent models:
List<ParentModel> parentModels = new ArrayList<ParentModel>();

 private ViewRenderer childViewRenderer() {
        ViewBinder.Binder<ChildModel> childBinder = new ViewBinder.Binder<ChildModel>() {
            @Override
            public void bindView(@NonNull ChildModel model, @NonNull ViewFinder finder, @NonNull List<Object> payloads) {
                finder.setOnClickListener(R.id.ibDelete, new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                String parent_id = model.getParentId();
                                for (ParentModel pm : parentModels) {
                                    if (pm.getId().equals(parent_id)) {
                                        pm.getItems().remove(model);
                                    }
                                }
                                parentAdapter.setItems(parentModels);
                            }
                        });
            }
        };

        return new ViewBinder<>(
                R.layout.child_item,
                ChildModel.class,
                childBinder
        );
    }

=====================================================================

Here is my parent view renderer:

 private ViewRenderer parentViewRenderer() {
        return new CompositeViewBinder(
                R.layout.parent_item,
                R.id.rvChild,
                ParentModel.class,
                (model, finder, payloads) -> finder
                        .setOnClickListener(R.id.ibDelete, (v -> onLocationDeleteClicked(model)))
        ).registerRenderer(childViewRenderer());
    }

**Comment by vivchar** [comment]
Looks fine, need to debug and investigate, please use the stackoverflow. I have no time to debug your code. Thanks.
