### ISSUE TITLE
Simple thought

### ISSUE THREAD

**Issue by dipcore** [vivchar/RendererRecyclerViewAdapter#22]
Probably in the adapter it is better to use something like:
```
    @NonNull
    protected final Map<Integer, ViewRenderer> mRenderers = new HashMap<>();
```

And later in the  adapter methods just check *mRenderers.get(type) == null*
for instance:

```
    public void registerRenderer(@NonNull final ViewRenderer renderer) {
            mRenderers.put(renderer.getType(), renderer);
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(final ViewGroup parent, final int type) {
        ViewRenderer renderer = mRenderers.get(type);
        if (renderer != null)
            return renderer.createViewHolder(parent);
        throw new RuntimeException("Could not find renderer of type: " + type);
    }
```

etc

**Comment by vivchar** [comment]
Thank you for your suggestion, but I already had that implementation, and it has some limitations. Currently I reworked it. You can look at version 1.x.x if you want.

I am closing this card.

**Comment by dipcore** [comment]
Could you give me more details about limitations you mention? I'm currently use similar solution in one of my project and would like to avoid big refactoring in future.
