### ISSUE TITLE
createViewHolder of ViewRenderer is called as many times as there are items in list

### ISSUE THREAD

**Issue by ghost** [vivchar/RendererRecyclerViewAdapter#24]
First of all - thank you for your lib.
I'm using it with ViewRenderer, as I have complex list items and prefer to write my own renderer for it. Also - I'm using CompositeViewRenderer. And here is the problem - createViewHolder of child view renderer is called for all items in list of childs, while I believe it should be called as many times as there items on screen. It is problem because my views are "heavy" and full list inflating takes time. Not a problem if you have only list one on screen, but I have viewpager with lists on every page, and page swiping is laggy even on modern phone.
My createViewHolder method is absolutely simple:

`	override fun createViewHolder(parent: ViewGroup?): GameEventViewHolder {
		return GameEventViewHolder(inflate(R.layout.list_item_game_event_constraint, parent))
	}`

Maybe I'm using it in wrong way?

**Comment by vivchar** [comment]
Thanks! I have no a chance to check it. Could you provide more info? Which flags of recyclerView do you use? I think it is default behavior of recyclerView or you use some special flags. Could you check my samples?

**Comment by ghost** [comment]
I investigated deeper, and it seems to behave in following way - updating\adding CompositeViewModel child and calling notifyItemChanged(compositeViewModelPosition) causes all children items of this CVM to be recreated (not refreshed!), even if they are not visible. In my there are only 3,5 child items on screen, but createViewHolder and bindItem is called for all 13 children of this CVM. Right now I have only one CVM per screen, and children number is not higher than 13-14, so I can't check RRVA behavior if there is more group\child items in list.
Regarding flags - either I don't understand the question, or I just use defaults.
Regarding default RV behavior - as far as I understand it creates (visible items number + 3..4) views, and then recycles them. But it is not true in my case with RRVA.
Regarding samples - I read them when I just discovered RRVA and started adding it to the project.
In theory, is it possible for you to add methods to control inner adapters from CompositeViewModel? I mean - notifyItem*. For now I can't figure how to get access to this adapter, maybe I'm missing something? Thank you in advance.

**Comment by vivchar** [comment]
Could you provide your sources?

**Comment by vivchar** [comment]
I checked it on my samples and it works as expected. I commented all sections exclude the First Stargazers.
In section First Stargazers I see 2.5 items, and the onCreateViewHolder calls 3 times.

Please investigate your sources. So it is a bug in your code. To receive a help please use the stackoverflow.

If you find any evidence/steps to reproduce then please reopen this issue.
