### ISSUE TITLE
How to use GridLayoutManager with child view inside nested recyclerview ?

### ISSUE THREAD

**Issue by varungpt** [vivchar/RendererRecyclerViewAdapter#27]
By default child RecyclerView uses LinearLayoutManager, how to change this to use GridLayoutManager?
Is there any other way to show child items as grid instead of horizontal layout?

Stackoverflow is not allowing me to create a new tag as I do not have enough reputation.

**Comment by vivchar** [comment]
No need to create the tag. Just use the "RendererRecyclerViewAdapter" word.

Please look at the [documentation](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Customization-of-Composite-Items) it will help you.

```
public class YourCompositeViewBinder extends CompositeViewBinder<YourCompositeModel> {
	//...
	@Override
	protected RecyclerView.LayoutManager createLayoutManager() {
		return new AnyLayoutManager();
	}
}
```
