### ISSUE TITLE
Version 2.7.0 is missing

### ISSUE THREAD

**Issue by TheJuki** [vivchar/RendererRecyclerViewAdapter#29]
https://oss.sonatype.org/content/groups/staging/com/github/vivchar/RendererRecyclerViewAdapter/2.7.0/

Version 2.7.0 seems to missing from the staging environment.

**Comment by vivchar** [comment]
Thanks! By some reason it was removed.
Please use this
```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
implementation 'com.github.vivchar:RendererRecyclerViewAdapter:2.7.0-SNAPSHOT'
```
