### ISSUE TITLE
Any plan to upgrade to Kotlin?

### ISSUE THREAD

**Issue by deckyfx** [vivchar/RendererRecyclerViewAdapter#35]
While current version is working  in kotlin, is there any plan to upgrade the source code to kotlin too?
i tried to manually convert them one by one, but it keep get cyclic error betwen * types and ViewModel ViewHolder generic types.

**Comment by vivchar** [comment]
Hi, Currently I don't want to migrate to Kotlin, because it forses projects without Kotlin use Kotlin.
Maybe in future I will add separated project. But I don't see any serious reason
