### ISSUE TITLE
Access CompositeViewBinder adapter

### ISSUE THREAD

**Issue by deckyfx** [vivchar/RendererRecyclerViewAdapter#36]
How to get child adapter from an CompositeViewBinder?

**Comment by vivchar** [comment]
You should not call child adapter from an CompositeViewBinder. Looks like you do something wrong.
If you provide the end goal and some code then maybe I can help you.

Also please look at the wiki https://github.com/vivchar/RendererRecyclerViewAdapter/wiki
Maybe you able to find another solution for your end goal.
