### ISSUE TITLE
how to access composite item recyclerview for snap

### ISSUE THREAD

**Issue by alimousavi71** [vivchar/RendererRecyclerViewAdapter#37]
how to access composite item recyclerview  for add snap helper for image slider and other config recyclerview?
**### i can create view such as image in this library ?**
**Problem is Slider**
![New Mockup 1 copy 5](https://user-images.githubusercontent.com/25837589/60737269-63704880-9f6f-11e9-8606-846cc9b85371.png)

**Comment by alimousavi71** [comment]
Please Help Me

**Comment by vivchar** [comment]
Hey, you should extend `CompositeViewBinder` class and override `createCompositeViewHolder` method:
```
protected CompositeViewHolder createCompositeViewHolder(@Nullable final ViewGroup parent) {
	final CompositeViewHolder compositeViewHolder = super.createCompositeViewHolder(parent);
	new LinearSnapHelper().attachToRecyclerView(compositeViewHolder.recyclerView);
	//access to composite item recyclerview
	return compositeViewHolder;
}
```

and then you can use your extended composite binder =)

**Comment by alimousavi71** [comment]
hi thanks

**Comment by alimousavi71** [comment]
please run image example as sample 
in this sample very useful in shop and other app application
please 😉

**Comment by vivchar** [comment]
Currently I don't have a time :( Welcome to pull request :)

**Comment by alimousavi71** [comment]
Im Win Thanks For All 
![image](https://user-images.githubusercontent.com/25837589/60824385-bee44580-a1be-11e9-9dd8-c1e954c84c0e.png)
See Video For All Section This [Link](https://www.youtube.com/embed/u4AGMpDoX7I)
