### ISSUE TITLE
RecyclerViewHolder.java

### ISSUE THREAD

**Issue by AnguelSC** [vivchar/RendererRecyclerViewAdapter#4]
Hi, it is not defined in recycler in the document,
```
public class RecyclerViewHolder
		extends CompositeViewHolder
{
	public RecyclerViewHolder(@NonNull final View view) {
		super(view);
		recyclerView = (RecyclerView) view.findViewById(R.id.recycler_view);
	}
}
```

 and how to add the adapter to this.

**Comment by vivchar** [comment]
Hi, It is just an example how to use the CompositeViewHolder.

If you use the CompositeViewRenderer then it will be added automatically. Please see this 
https://github.com/vivchar/RendererRecyclerViewAdapter/blob/f84631760d6bdc5b5c736b86ffc034962ceb5443/rendererrecyclerviewadapter/src/main/java/com/github/vivchar/rendererrecyclerviewadapter/CompositeViewRenderer.java#L49

I will create a wiki page later. Thank you for your feedback! :)
FYI: please use the latest version - v1.2.4. I released it today

**Comment by vivchar** [comment]
@AnguelSC I added a simple documentation, please look at this:
https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-Composite-Items
