### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by abdurahmanadilovic** [vivchar/RendererRecyclerViewAdapter#43]
First of all, awesome library, I have been using it for all of my apps.
So my question is, what would be the easiest way to support drag and drop with this library? I use this library to have lists with different row types and one obvious thing with drag and drop feature is that I don't want the user to drag and drop a row into rows of a different type.

**Comment by vivchar** [comment]
Thanks! 

In my project I used documentation to implement it:
https://developer.android.com/reference/androidx/recyclerview/widget/ItemTouchHelper.Callback

I believe that you can find a library to have the easiest way to support this.

Also feel free to make pull request :)

**Comment by abdurahmanadilovic** [comment]
Thanks for the quick reply! I found that link very helpful. 
One question, is there a way for me to get to the actual RecyclerView.ViewHolder so I can pass it back to the ItemTouchHelper in case I want the drag to happen from a specific view?

**Comment by vivchar** [comment]
I'm not sure that you need a viewHolder.

https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf

**Comment by abdurahmanadilovic** [comment]
[The second part](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-6a6f0c422efd) of that article uses the "drag handles" which requre passing RV.ViewHolders around. I just looked at the ViewBinder class, it seems like bindView method just passes down the viewFinder and not the whole ViewHolder.

**Comment by vivchar** [comment]
you will receive viewHolder from Callback:
```
public class YourListener implements OnStartDragListener {
    //...
    @Override
    public void onStartDrag(RecyclerView.ViewHolder viewHolder) {
        mItemTouchHelper.startDrag(viewHolder);
    }
}
```

**Comment by abdurahmanadilovic** [comment]
I will have to call that listener from my Binder since it is just a touch listener on the "drag handler" view, like so 
``` 
holder.handleView.setOnTouchListener(new OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
            if (MotionEventCompat.getActionMasked(event) == 
                    MotionEvent.ACTION_DOWN) {
                mDragStartListener.onStartDrag(holder);
            }
            return false;
        }
    });
```
So basically the listener (parent activity) will pass that RV.ViewHolder to the ItemTouchHelper class.

I think the solution here is to override a couple of methods from ViewBinder class 

```
@Override
	@SuppressWarnings("unchecked")
	public void bindView(@NonNull final M model, @NonNull final ViewHolder finder) {
		mBinder.bindView(model, finder.getViewFinder(), new ArrayList<>());
	}

	@Override
	@SuppressWarnings("unchecked")
	public void rebindView(@NonNull final M model, @NonNull final ViewHolder finder, @NonNull final List<Object> payloads) {
		mBinder.bindView(model, finder.getViewFinder(), payloads);
	}
```

Like so

```
 override fun rebindView(model: EpisodeUIModel, finder: ViewHolder, payloads: MutableList<Any>) {
        // call custom binder and pass the ViewHolder
       // customBinder.bind(model, finder, finder.getViewFinder(), payloads)
    }

```

So instead of passing just a viewHolder.getViewFinder() I can pass that and the whole viewHolder class.

Is that a good approach?

**Comment by vivchar** [comment]
not sure, possible you should extends RendererRecyclerViewAdapter and implement ItemTouchHelperAdapter
maybe this will allow to avoid a call from Binder

**Comment by vivchar** [comment]
I'm closing this issue, looks like no need to do any fixes on library side.
Feel free to reopen
