### ISSUE TITLE
How to add a custom paging adapter 

### ISSUE THREAD

**Issue by mathemandy** [vivchar/RendererRecyclerViewAdapter#46]
Hello, I read the instructions and I know this issue page is for issue only reporting but I feel my question can only be answered by you. 

Question. 
How do I add a custom adapter implementation to your adapter or ViewBinder. 
My implementations involves various having multiple composite items and one of the items requires me to have an auto scroll recyclerview for banner items. (Looping viewapager) 

I’d like to know if it can be integrated in your adapter

**Comment by vivchar** [comment]
Hey, As I understood you need `CompositeViewBinder`.
You can use only adapter which extends `RendererRecyclerViewAdapter`. 
To use it you should extend `CompositeViewBinder` and override `createAdapter` method.

See samples there https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Customization-of-Composite-Items
