### ISSUE TITLE
Unable to resolve model methods ?

### ISSUE THREAD

**Issue by drmkraja** [vivchar/RendererRecyclerViewAdapter#49]
I'm new to this library, I tried to implement the library version 3.0.3. In my ViewRenderer, Unable to resolved the model methods like model.getText() ? Is this Issue with new version or my implementation is wrong ?

CODE 

`public class DashboardFragment extends Fragment {

    private DashboardViewModel dashboardViewModel;

    private RendererRecyclerViewAdapter mRecyclerViewAdapter;

    public View onCreateView(@NonNull LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

        dashboardViewModel = new ViewModelProvider(this).get(DashboardViewModel.class);

        View root = inflater.inflate(R.layout.fragment_dashboard, container, false);

        mRecyclerViewAdapter = new RendererRecyclerViewAdapter();
        mRecyclerViewAdapter.registerRenderer(getYourViewBinder());
        mRecyclerViewAdapter.setItems(getSquareItems());

        final RecyclerView recyclerView = (RecyclerView) root.findViewById(R.id.recycler_view);
        recyclerView.setAdapter(mRecyclerViewAdapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));

        return root;
    }

    private ViewRenderer getYourViewBinder() {
        return new ViewRenderer(
                R.layout.item_futures, /* your item layout */
                RectViewModel.class, /* your model class */
                (model, finder, payloads) -> finder
                        .setText(R.id.title, model.getText()) /* unable to resolve model methods */
                        .setText(R.id.price, model.getID())
        );
    }

    public static class RectViewModel implements ViewModel {

        private int mID;
        private final String mText;

        public RectViewModel(final int ID, final String text) {
            mID = ID;
            mText = text;
        }

        public int getID() {
            return mID;
        }

        public String getText() {
            return mText;
        }
    }

    public List<ViewModel> getSquareItems() {
        final ArrayList<ViewModel> items = new ArrayList<>();
        for (int i = 0; i < 50; i++) {
            items.add(new Indices("Hell0 ", String.valueOf(i)));
        }
        return items;
    }
} `

**Comment by vivchar** [comment]
Looks like you missed  the generic param <>:
```diff
-new ViewRenderer
+new ViewRenderer<>
```

```
    return new ViewRenderer<>(
            R.layout.item_futures, /* your item layout */
            RectViewModel.class, /* your model class */
            (model, finder, payloads) -> finder
                    .setText(R.id.title, model.getText()) /* unable to resolve model methods */
                    .setText(R.id.price, model.getID())
    );
```

**Comment by drmkraja** [comment]
Thanks. I was trying to Implement DiffCallBack. But it is not working as expected. The Items are getting added to the list. I need to update only the values for that changed Item.

Can you please check this gist > [GIST](https://gist.github.com/drmkraja/7e6fc375728f235d752db5ff22a1ee8a )

**Comment by vivchar** [comment]
1. Please look at the samples and the doc.
2. Investigate your code here:
```
    public List<Indices> getItems() {
        items.add(new Indices(001, "APPLE", "15"));
        items.add(new Indices(002, "GRAPES", "50"));
        return items;
    }

    private void updateItems() {
        items.add(new Indices(001, "APPLE", "15"));
        items.add(new Indices(002, "GRAPES", "56"));
        mRecyclerViewAdapter.setItems(items);
        mRecyclerViewAdapter.notifyDataSetChanged();
    }
```
3. If you find a bug - please create an issue. 
4. Otherwise use stackoverflow.com - you will help me to promote this library.

**Comment by drmkraja** [comment]
unable to resolve it... I have added a question in stackoverflow too
https://stackoverflow.com/questions/61810466/unable-to-update-specific-values-using-diff-util
