### ISSUE TITLE
Position of ViewModel?

### ISSUE THREAD

**Issue by frankenten13** [vivchar/RendererRecyclerViewAdapter#5]
I have a List<ViewModel> allModel. allModel have size is 15. I see bindView in ViewRerender have paramete is ViewModel, not positon, how i get postion when click the row, can't you help me?
Thanks.

**Comment by vivchar** [comment]
What task/issue do you decide when you want to use the position?
as option you can use `holder.getAdapterPosition()`

**Comment by klamborowski** [comment]
It's a bit old question, but now, when `ViewRenderer` is deprecated, is still actual. 

How can we obtain ViewModel position  in `ViewBinder`?

**Comment by vivchar** [comment]
How do you want to use the position?
Currently it is impossible. I don't see any reason to use the position inside the bind method.
If you need the position inside the bindView method then you use it wrong.
Please give me more info/samples and I will try to help you.

**Comment by klamborowski** [comment]
Ok. First item in my recycler is always header. It has rounded corners on top and rect corners on bottom. Next items are presented with all 4 rounded corners,  may have one of 3 types and all type have different view. But first item after header should have rect top corners. In that case, when I reusing/rebinding holder I should decide how it top corners should look like.

1. First item - always Header - rounded top corners, rect bottom corners
2. Second item - type is not known, it will come from API - rounded top corners, rect bottom corners
3. Next items - type is not known, it will come from API - rounded top corners, rounded bottom corners

Imho to solve that case I need to know position of holder.

**Comment by vivchar** [comment]
You should create three `ViewModel` and three `ViewBinder`. You should not use one ViewModel for this.

FYI: adapter/bindView method should not contain any logic how to show view. It should contain only binding of a view. Read my articles and you will understand my policy.

**Comment by klamborowski** [comment]
I think we have a little misunderstanding here. I will try to explain it more clearly.

I already have 3 ViewModel and 3 ViewBinder:

1. HeaderViewBinder for HeaderViewModel
2. Type1ItemViewBinder for Type1ViewModel
3. Type2ItemViewBinder for Type2ViewModel
4. Type3ItemViewBinder for Type3ViewModel

We put HeaderViewModel as first adapter item.
Next we can put either Type1ViewModel, Type2ViewModel or Type3ViewModel. It will come form API. But always first item after HeaderViewModel should have different top corners.


![recycler](https://user-images.githubusercontent.com/4972310/46402943-68af1700-c701-11e8-9bda-8da2c4a3eafa.png)

**Comment by vivchar** [comment]
Oh, ok. You should use additional parameter.
ex: `Type1ViewModel(int ID, boolean showTopCorners, boolean showBottomCorners)`

So when you map your models to `ViewModel`s you know positions and can set these parameters/flags.

```
	ArrayList<Object> serverItems = new ArrayList<>();
	ArrayList<Object> models = new ArrayList<>();
	for (int i = 0; i < serverItems.size(); i++) {
		final boolean showBottomCorners = i <= 1;
		models.add(new Type1ViewModel(showBottomCorners));
	}
```
