### ISSUE TITLE
How to get item position after updating items

### ISSUE THREAD

**Issue by behnamnazarpak** [vivchar/RendererRecyclerViewAdapter#50]
Hello and thank you for your cool library <3
i have an implement of ViewBinder and in this binder i set position into models
like this :
`public class PositionViewBinder<M extends PositionViewBinder.PositionViewModel> extends ViewBinder<M> {

    public PositionViewBinder(final int layoutID,
                              @NonNull final Class<M> type,
                              @NonNull final Binder<M> binder) {
        super(layoutID, type, binder);
    }

    @Override
    public void bindView(@NonNull final M model, @NonNull final ViewHolder viewHolder) {

        super.bindView(model, viewHolder);
        model.setPosition(viewHolder.getAdapterPosition());
    }

    public static class PositionViewModel implements ViewModel {
        private int position;

        public int getPosition() {
            return this.position;
        }

        void setPosition(int position) {
            this.position = position;
        }
    }
}`

but i need to update this position after another item removed because the position field hold old position
how could i achieve this?

**Comment by vivchar** [comment]
Hi. Thanks!

It is not correct way to use ViewBinder to update or set position. Ideally you should not use position.

Could you say for what you need position?


Please look at these cards:
https://github.com/vivchar/RendererRecyclerViewAdapter/issues/12
https://github.com/vivchar/RendererRecyclerViewAdapter/issues/5

**Comment by behnamnazarpak** [comment]
I have two button inside each item of adapter and when i click this buttons, after doing some io the item must be removed list.

**Comment by vivchar** [comment]
You should add special flag for button visibility to your ViewModel class:
```
class YourViewModel implements ViewModel {
    bool isFirstButtonVisible;
    bool isSecondButtonVisible;
}
```

When you click at the button you should update your flag in your item
```
ArrayList<YourViewModel> items = getItems();
adapter.setItems(items);
adapter.notify()
//...

void onFirstButtonClicked(YourViewModel model) {
  items.findAndReplace(YourViewModel(!model.isFirstButtonVisible, model.isSecondButtonVisible));

  adapter.setItems(items);
  adapter.notify()
}
```

**Comment by behnamnazarpak** [comment]
Thanks but i need to remove item not jua visibility of buttons 
 Imagine you have a list of friends request then each item have two button when you click on accept or reject button after some io and networking , the item must be removed from list

**Comment by vivchar** [comment]
then you just should remove item from the list.
```
void onFirstButtonClicked(YourViewModel model) {
  items.findAndRemove(model);

  adapter.setItems(items);
  adapter.notify()
}
```

**Comment by behnamnazarpak** [comment]
Thanks !
Another question 
How can i show/hide loading view that exist inside of items (already i pass viewHolder to access the rootView) ?

**Comment by vivchar** [comment]
add special flag to your model, and update when it needs
```
class YourViewModel implements ViewModel {
    bool isLoading;
}
```
