### ISSUE TITLE
How to create a  StargazerViewRenderer with version 3.0 ?

### ISSUE THREAD

**Issue by drmkraja** [vivchar/RendererRecyclerViewAdapter#51]
I'm trying to create a [StargazerViewRenderer like this ](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/d6d61c8778ee719ef701a8ca15d264161fe0d48b/example/src/main/java/com/github/vivchar/example/pages/github/items/stargazer/StargazerViewRenderer.java) which is compatible with latest version 3.0

Since there are a lot of terms & changes. I tried following this [doc](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-ViewState). But still I had Issues. I have attached my code in this [Gist](https://gist.github.com/drmkraja/f14f38f1fc8a88047123c3907ba0c724)

I have added this question in [stackoverflow ](https://stackoverflow.com/questions/62862774/how-to-implement-viewrenderer-for-multi-selection-recyclerview)also

**Comment by vivchar** [comment]
You should switch to `v3.0.0` branch, there are all samples:
**https://github.com/vivchar/RendererRecyclerViewAdapter/blob/v3.0.0/example/src/main/java/com/github/vivchar/example/pages/github/items/StargazerViewRenderer.java**

**Comment by drmkraja** [comment]
Sorry I missed that branch. Thanks a lot for the link . It helped me to implement multiple selection Recyclerview like Stargazer. 

Now I can select Multiple items. But I want to change the selection Mode to only one item?  I tried it in [my Gist here](https://gist.github.com/drmkraja/f14f38f1fc8a88047123c3907ba0c724). 
How can I get the selected items list in `StargazerViewRenderer` to allow one item selection ?
Please let me know the best way to achieve this ?

**Comment by vivchar** [comment]
in this case you should use your model to set/reset check box.
add `isChecked` field to your `Category` model and set/reset after clicks.
then you can remove `ViewState`

**Comment by drmkraja** [comment]
Updated the [gist ](https://gist.github.com/drmkraja/f14f38f1fc8a88047123c3907ba0c724) as per your suggestion. But How can I reset old selected items on 'SINGLE SELECTION MODE' ?

**Comment by vivchar** [comment]
you should update your item list and put it to adapter and call notifydatasetchanged

Sorry, but your questions are not related with the library, please use stackoverflow.com

**Comment by drmkraja** [comment]
Unable to resolve this. I have added the question in stackoverflow. If you have time, Please answer it ...
https://stackoverflow.com/questions/63009064/how-to-set-single-selection-in-recyclerview
