### ISSUE TITLE
Paging 3.0 or Load More Indicator ?

### ISSUE THREAD

**Issue by drmkraja** [vivchar/RendererRecyclerViewAdapter#52]
HI, I'm using this library in my app. I'm planning to support pagination in my recycler view. I have seen the [Load More Indicator](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-Load-More-Indicator) which is bundled in the library which looks good. But Since Google has released [paging 3.0.](https://developer.android.com/topic/libraries/architecture/paging/v3-overview) Can I use paging 3.0 with this library or do u suggest to go with [Load More Indicator](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-Load-More-Indicator) ?

**Comment by vivchar** [comment]
Hi, I didn't used the paging 3.0 yet. But you always can try it and send pull request if needed.
Currently you have ability to use the Load More Indicator.
