### ISSUE TITLE
change composite item in parent

### ISSUE THREAD

**Issue by alimousavi71** [vivchar/RendererRecyclerViewAdapter#53]
hello im need change parent item text in composite  please help
please see attachment im need change [Mr Tahvil] TextView in parent adapter dynamic!
![image](https://user-images.githubusercontent.com/25837589/97121574-89a59300-1734-11eb-8bde-940a22ace7c0.png)
![image](https://user-images.githubusercontent.com/25837589/97121589-a641cb00-1734-11eb-89fc-f1e717e5b29d.png)

**Comment by vivchar** [comment]
Hi. Looks like this question is not related with the library. I don't see enough information to let you answer.
Feel free to read [the documentation](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki).
Also please check [this item](https://github.com/vivchar/RendererRecyclerViewAdapter#communication). I mean that looks like you should use the stackoverflow to get an answer.
