### ISSUE TITLE
Question :- How can I achieve Horizontal Recycler View inside Vertical Recycler View with load more in both horizontal and vertical recyclers ?

### ISSUE THREAD

**Issue by praveenshharma** [vivchar/RendererRecyclerViewAdapter#6]

**Comment by vivchar** [comment]
- [LoadMore](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/master/example/src/main/java/com/github/vivchar/example/pages/simple/LoadMoreFragment.java#L45);
- [Nested RecyclerView](https://github.com/vivchar/RendererRecyclerViewAdapter/blob/master/example/src/main/java/com/github/vivchar/example/pages/simple/CompositeViewRendererFragment.java#L38);

To implement load more inside Nested RecyclerView you should extend CompositeViewRenderer and implement load more inside createViewHolder method.

```
	...
	@Override
	public YourViewHolder createCompositeViewHolder(ViewGroup parent) {
		YourViewHolder viewHolder = new YourViewHolder(inflate(R.layout.your_recycler_view, parent));
		viewHolder.getRecyclerView().addOnScrollListener(new YourEndlessScrollListener() {
			public void onLoadMore() {
				viewHolder.getAdapter().showLoadMore();
//				mYourListener.onLoadMore();
			}
		};
	}
	...

**Comment by praveenshharma** [comment]
Thankyou for your reply, can you just tell me how can I use your source code to do this ?
Is this doable by your library ? or I can just use the Composite View Renderer section and edit it with Load More ?

**Comment by vivchar** [comment]
Please look at [the wiki page](https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-Composite-Items) about Composite Items.

yes, you should modify the createCompositeViewHolder section.
