### ISSUE TITLE
Cannot Resolve ViewModel

### ISSUE THREAD

**Issue by TheJuki** [vivchar/RendererRecyclerViewAdapter#7]
```
Error:Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.thejuki.kformmaster.model.BaseFormElement, unresolved supertypes: com.github.vivchar.rendererrecyclerviewadapter.ViewModel
```

I am trying to use my Kotlin form library I created: https://github.com/TheJuki/KFormMaster
It implements your library to handle the different types of views. However, I cannot build my Android application that uses my library. Any ideas as to why ViewModel cannot be resolved? BaseFormElement is here: https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/model/BaseFormElement.kt

I added this my gradle.build:
`implementation "com.thejuki:k-form-master:1.2.0"`

**Comment by vivchar** [comment]
@TheJuki I am not sure that it is problem of my library.

1. Try to replace to `api "com.thejuki:k-form-master:1.2.0"`;
2. Try to sync your project.

**Comment by TheJuki** [comment]
Same issue. It may be related to Proguard not keeping the filename. I'll try working with that.

**Comment by TheJuki** [comment]
Okay. My last update does work now.
So, in my form library I am using 
`compile "com.github.vivchar:RendererRecyclerViewAdapter:2.5.0".` 
This lets the example project and my seperate Android project run. I still don't understand gradle's api and implementation.

**Comment by vivchar** [comment]
> It may be related to Proguard not keeping the filename. I'll try working with that.

I am not sure that it is Proguard issue, you can temporary disable Proguard and check it (or to use debug build).

>Try to replace to api "com.thejuki:k-form-master:1.2.0";

I mean that you should replace it in the app/build.gradle.

>My last update does work now.

does not work OR work?

**Comment by TheJuki** [comment]
It works now. Using compile "com.github.vivchar:RendererRecyclerViewAdapter:2.5.0" instead of implementation "com.github.vivchar:RendererRecyclerViewAdapter:2.5.0" works.
