### ISSUE TITLE
Renderer for model type

### ISSUE THREAD

**Issue by viktorot** [vivchar/RendererRecyclerViewAdapter#8]
Hello,

I was looking to migrate to the latest version and saw that you removed the types that were bound to the Renderer what it was registered with the Adapter. 

I was wondering is there anyway to implement/emulate that behavior in the latest version?

It can theoretically be done with different model types, but receiving some type when inflating the layout and then deciding which layout to inflate would be much cleaner imho.

Regards,
Viktor

**Comment by vivchar** [comment]
Hi,

>I was looking to migrate to the latest version and saw that you removed the types that were bound to the Renderer what it was registered with the Adapter.

Yes, I removed the types, I think that it does not make any sense.

> I was wondering is there anyway to implement/emulate that behavior in the latest version?
> It can theoretically be done with different model types, but receiving some type when inflating the layout and then deciding which layout to inflate would be much cleaner imho.

Yes, you should extend your model. Why do you want to change a type but don't change a renderer and a model? It looks strange. I would be help more if you provide an sample/code.

**Comment by viktorot** [comment]
So... my model has a structire simmilar to this

```kotlin
class Item(val id: Int, val size: Int, val title: String)
````

which I recieve from the backend. The RecyclerView in my case renders more-or-less the same item but with different sizes, that that is defined by the ```size``` property, so I reuse the complete ViewHolder.

In the older version, ```size``` mapped perfectly into the library's structure. I registered my renderes, inflated the correct view and all was well.

With the latest version I would need to define a new class for evert possible value of the ```size``` property. It doesn't sound that bad looking at the sample, but the actual class has cca. 15 properties and 10 possible size values. I would need to define 10 sublcasses of the base model and override all the properties in each one. The solution would be semantically correct, but not so much pragmatically.

I'm now looking for ways of integrating my current structure in the latest version and have hit a brick wall.

**Comment by vivchar** [comment]
I am not sure that I understood correctly how do you use the `size` field. Could you provide your ViewRenderer or similar ViewRenderer?

**Comment by viktorot** [comment]
The rendered looks something like this:

```kotlin
class CardRenderer(type: Int, context: Context) {
    fun onCreateViewHolder(parent: ViewGroup?): CardBaseViewHolder {
        val layoutId = when (size) {
            0 -> R.layout.item_small
            1 -> R.layout.item_normal
            2 -> R.layout.item_large
        }
        // inflate layout & return holedr
    }
    // other overrides
}
```

So, the ```type``` parameter that was present in the last version actually represented the size/layout that needs to be inflated for a specific model. In this way I got away with having one model for all renderers. Thy layout type was selected according to a property in the model.

With the new library version this is not possible. My question is weather there is a way to emulate the old behavior with the latest release.

**Comment by vivchar** [comment]
OK, thanks, I understood. But how do you get the `size` inside the `onCreateViewHolder`? Did you hardcoded all values on your client? If not - It looks like you created a workaround to implement it.

I see only one solution - yes, you need to define subclasses of your model:
```java
private class YourViewBinder <M extends YourModel> extends ViewBinder<M> {

	public YourViewBinder(final int layoutID, @NonNull final Class<M> type) {
		super(layoutID, type, (model, finder, payloads) -> {
			finder.setText(R.id.text, model.getText());
		});
	}
}

private class YourModel implements ViewModel {
	public String getText() { return getClass().getSimpleName(); }
}

private class SmallModel extends YourModel {}
private class NormalModel extends YourModel {}
private class LargeModel extends YourModel {}

//...
adapter.registerRenderer(new YourViewBinder<>(R.layout.small_item, SmallModel.class));
adapter.registerRenderer(new YourViewBinder<>(R.layout.normal_item, NormalModel.class));
adapter.registerRenderer(new YourViewBinder<>(R.layout.large_item, LargeModel.class));
```
