### ISSUE TITLE
Migration to v2.0 Wiki

### ISSUE THREAD

**Issue by TheJuki** [vivchar/RendererRecyclerViewAdapter#9]
https://github.com/TheJuki/RendererRecyclerViewAdapter/wiki/Migration-to-v2.0

I created a small migration guide for your Wiki.  Having that wiki would have helped myself a lot when doing the same migration.

**Comment by duartebarbosadev** [comment]
+1

On this wiki
https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Quick-start-with-the-Renderer-Adapter

it says:
Create a ViewRenderer 
it should say View Binder? Because ViewRenderer is deprecated

**Comment by vivchar** [comment]
@TheJuki  thank you! I will apply it

**Comment by vivchar** [comment]
@PedroBarbosaPT thank you. I fixed it

**Comment by vivchar** [comment]
https://github.com/vivchar/RendererRecyclerViewAdapter/wiki/Migration-to-2.5.0
